### ISSUE TITLE
LiteDB的一点疑问

### ISSUE THREAD

**Issue by sgf** [lidanger/LiteDB.wiki_Translation_zh-cn#1]
1.如果 某个集合SetA的某字段Field1需要建立索引
那么针对SetA的操作，每次 做查询的时候（增删改查） 都要 执行EnsureIndex  这个函数么？

2.查询的时候
没看到 GetOrUpdate 这种类似的Api（有一个 Upsert 但是似乎无法附加条件？）。
那么会不会造成  并发查询的时候 数据不一致。
即查询的时候没查到，但是执行插入的时候，却因为其他地方的操作，已经存在了？

**Comment by lidanger** [comment]
@sgf 
1、不需要。
2、这个应该不会吧，组件有文档级的锁
